name: app_badger
description: "A Flutter plugin to update app badge count on Android (including Xiaomi)."
version: 0.0.1
homepage: https://github.com/ajinkya446/app_badger
repository: https://github.com/ajinkya446/app_badger

environment:
  sdk: ^3.7.2
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.ajinkya.app_badger
        pluginClass: AppBadgerPlugin